version: "2"
services:
  workspace:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "yarn global add @angular/cli && yarn && ng build --watch --poll 5 --base-href=/sw"
